name: flutter_nordic_dfu
description: A new flutter plugin project.
version: 0.0.1+1
author: fengqiangboy <fengqiangboy@gmail.com>
homepage: https://github.com/fengqiangboy/flutter-nordic-dfu

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.timeyaa.flutternordicdfu
    pluginClass: FlutterNordicDfuPlugin
